### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by untocodes** [deadman96385/twrp_device_lenovo_cube#1]
Hello. 

I found this repo a few days ago while searching information about this device.

I tried building it myself, got a clean build but didn't manage to get it booted.

Did you ever get TWRP built with this device tree booting on the Lenovo Smart Clock and if you did how did you do it? 

- Unto K

**Comment by Wh1terat** [comment]
*bump*
Same thing for me.

**Comment by untocodes** [comment]
@Wh1terat, he responded to me in twitter. Apparently he had no luck getting it to boot. If you want to talk with me about my findings, feel free to message me on Discord: ``Unto#0001``
